spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/docuflow

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
